/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hn.uth.pa1.parcial2.app;

import hn.uth.pa1.parcial2.app.objetos.Vehiculo;
import hn.uth.pa1.parcial2.app.repositorio.VehiculoRepo;
import java.awt.Image;
import java.sql.Connection;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author karol
 */
public class Frm_Vehiculos1 extends javax.swing.JFrame {

    /**
     * Creates new form Frm_Vehiculos
     */
    public Frm_Vehiculos1() {
        initComponents();
        info();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblModelo3 = new javax.swing.JLabel();
        lblAnio3 = new javax.swing.JLabel();
        lblMarca3 = new javax.swing.JLabel();
        lblMotor3 = new javax.swing.JLabel();
        lblPrecio3 = new javax.swing.JLabel();
        lblTextAnio3 = new javax.swing.JLabel();
        lblTextPlaca3 = new javax.swing.JLabel();
        lblNombre3 = new javax.swing.JLabel();
        btnAnterior = new javax.swing.JButton();
        btnBuscar1 = new javax.swing.JButton();
        btnSiguiente = new javax.swing.JButton();
        lblPlaca1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblPrecio1 = new javax.swing.JLabel();
        lblImagen2 = new javax.swing.JLabel();
        lblFiltroAño1 = new javax.swing.JLabel();
        lblImagen3 = new javax.swing.JLabel();
        lblTextNombre1 = new javax.swing.JLabel();
        lblTextMarca1 = new javax.swing.JLabel();
        lblTextModelo1 = new javax.swing.JLabel();
        lblTextAnio1 = new javax.swing.JLabel();
        lblTextMotor1 = new javax.swing.JLabel();
        lblTextPlaca1 = new javax.swing.JLabel();
        lblTitulo = new javax.swing.JLabel();
        lblImagen1 = new javax.swing.JLabel();
        lblNombre1 = new javax.swing.JLabel();
        lblMarca1 = new javax.swing.JLabel();
        lblAnio1 = new javax.swing.JLabel();
        lblModelo1 = new javax.swing.JLabel();
        lblMotor1 = new javax.swing.JLabel();
        lblTextPrecio1 = new javax.swing.JLabel();
        btnVer1 = new javax.swing.JButton();
        lblPrecio2 = new javax.swing.JLabel();
        lblTextNombre2 = new javax.swing.JLabel();
        lblTextMarca2 = new javax.swing.JLabel();
        lblTextModelo2 = new javax.swing.JLabel();
        lblTextAnio2 = new javax.swing.JLabel();
        lblTextMotor2 = new javax.swing.JLabel();
        lblTextPlaca2 = new javax.swing.JLabel();
        lblNombre2 = new javax.swing.JLabel();
        lblMarca2 = new javax.swing.JLabel();
        lblAnio2 = new javax.swing.JLabel();
        lblModelo2 = new javax.swing.JLabel();
        lblMotor2 = new javax.swing.JLabel();
        lblTextPrecio2 = new javax.swing.JLabel();
        lblPlaca2 = new javax.swing.JLabel();
        btnVer2 = new javax.swing.JButton();
        lblTextPrecio3 = new javax.swing.JLabel();
        lblPlaca3 = new javax.swing.JLabel();
        lblTextModelo3 = new javax.swing.JLabel();
        lblTextMotor3 = new javax.swing.JLabel();
        lblTextNombre3 = new javax.swing.JLabel();
        lblTextMarca3 = new javax.swing.JLabel();
        btnVer3 = new javax.swing.JButton();
        txtFiltrarAnio = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblModelo3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblModelo3.setText("Modelo:");

        lblAnio3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblAnio3.setText("Año:");

        lblMarca3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblMarca3.setText("Marca:");

        lblMotor3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblMotor3.setText("Motor:");

        lblPrecio3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblPrecio3.setText("Precio:");

        lblTextAnio3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblTextAnio3.setText("texto año");

        lblTextPlaca3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblTextPlaca3.setText("texto placa");

        lblNombre3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblNombre3.setText("Nombre:");

        btnAnterior.setText("Anterior");
        btnAnterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnteriorActionPerformed(evt);
            }
        });

        btnBuscar1.setText("Buscar");
        btnBuscar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscar1ActionPerformed(evt);
            }
        });

        btnSiguiente.setText("Siguiente");
        btnSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSiguienteActionPerformed(evt);
            }
        });

        lblPlaca1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblPlaca1.setText("Placa:");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("3 / 6");

        lblPrecio1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblPrecio1.setText("Precio:");

        lblImagen2.setText("imagen2");

        lblFiltroAño1.setText("Filtrar por año:");

        lblImagen3.setText("imagen3");

        lblTextNombre1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblTextNombre1.setText("text nombre");

        lblTextMarca1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblTextMarca1.setText("texto marca");

        lblTextModelo1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblTextModelo1.setText("texto modelo");

        lblTextAnio1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblTextAnio1.setText("texto año");

        lblTextMotor1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblTextMotor1.setText("texto motor");

        lblTextPlaca1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblTextPlaca1.setText("texto placa");

        lblTitulo.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblTitulo.setText("Catálogo de Vehículos");

        lblImagen1.setText("imagen1");

        lblNombre1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblNombre1.setText("Nombre:");

        lblMarca1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblMarca1.setText("Marca:");

        lblAnio1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblAnio1.setText("Año:");

        lblModelo1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblModelo1.setText("Modelo:");

        lblMotor1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblMotor1.setText("Motor:");

        lblTextPrecio1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblTextPrecio1.setText("texto precio");

        btnVer1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnVer1.setText("Ver");
        btnVer1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVer1ActionPerformed(evt);
            }
        });

        lblPrecio2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblPrecio2.setText("Precio:");

        lblTextNombre2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblTextNombre2.setText("text nombre");

        lblTextMarca2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblTextMarca2.setText("texto marca");

        lblTextModelo2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblTextModelo2.setText("texto modelo");

        lblTextAnio2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblTextAnio2.setText("texto año");

        lblTextMotor2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblTextMotor2.setText("texto motor");

        lblTextPlaca2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblTextPlaca2.setText("texto placa");

        lblNombre2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblNombre2.setText("Nombre:");

        lblMarca2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblMarca2.setText("Marca:");

        lblAnio2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblAnio2.setText("Año:");

        lblModelo2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblModelo2.setText("Modelo:");

        lblMotor2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblMotor2.setText("Motor:");

        lblTextPrecio2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblTextPrecio2.setText("texto precio");

        lblPlaca2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblPlaca2.setText("Placa:");

        btnVer2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnVer2.setText("Ver");
        btnVer2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVer2ActionPerformed(evt);
            }
        });

        lblTextPrecio3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblTextPrecio3.setText("texto precio");

        lblPlaca3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblPlaca3.setText("Placa:");

        lblTextModelo3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblTextModelo3.setText("texto modelo");

        lblTextMotor3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblTextMotor3.setText("texto motor");

        lblTextNombre3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblTextNombre3.setText("text nombre");

        lblTextMarca3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblTextMarca3.setText("texto marca");

        btnVer3.setText("Ver");
        btnVer3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVer3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(285, 285, 285)
                        .addComponent(btnAnterior)
                        .addGap(104, 104, 104)
                        .addComponent(jLabel1)
                        .addGap(83, 83, 83)
                        .addComponent(btnSiguiente))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTitulo)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(511, 511, 511)
                                .addComponent(lblFiltroAño1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtFiltrarAnio, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(5, 5, 5)
                                .addComponent(btnBuscar1))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblImagen1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblImagen2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblImagen3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(181, 181, 181)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGap(226, 226, 226)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(lblPlaca2)
                                                    .addGap(18, 18, 18)
                                                    .addComponent(lblTextPlaca2))
                                                .addGroup(layout.createSequentialGroup()
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(lblMotor2)
                                                        .addComponent(lblAnio2))
                                                    .addGap(18, 18, 18)
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(lblTextAnio2)
                                                        .addComponent(lblTextMotor2))))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(lblMotor1)
                                                    .addComponent(lblAnio1)
                                                    .addComponent(lblPlaca1))
                                                .addGap(18, 18, 18)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(lblTextPlaca1)
                                                    .addComponent(lblTextAnio1)
                                                    .addComponent(lblTextMotor1))))
                                        .addGap(62, 62, 62)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(btnVer1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(btnVer2, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblNombre2)
                                            .addComponent(lblMarca2)
                                            .addComponent(lblModelo2)
                                            .addComponent(lblPrecio2))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblTextNombre2, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lblTextModelo2, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lblTextPrecio2)
                                            .addComponent(lblTextMarca2, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblNombre1)
                                            .addComponent(lblMarca1)
                                            .addComponent(lblModelo1)
                                            .addComponent(lblPrecio1))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(lblTextNombre1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(lblTextMarca1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(lblTextModelo1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(lblTextPrecio1)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblNombre3)
                                            .addComponent(lblPrecio3)
                                            .addComponent(lblMarca3))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblTextPrecio3)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(lblTextMarca3, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(lblTextModelo3, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(lblTextNombre3, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(63, 63, 63)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                        .addComponent(lblMotor3)
                                                        .addGap(18, 18, 18)
                                                        .addComponent(lblTextMotor3))
                                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                        .addComponent(lblPlaca3)
                                                        .addGap(18, 18, 18)
                                                        .addComponent(lblTextPlaca3))
                                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                        .addComponent(lblAnio3)
                                                        .addGap(30, 30, 30)
                                                        .addComponent(lblTextAnio3)))
                                                .addGap(62, 62, 62)
                                                .addComponent(btnVer3, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addComponent(lblModelo3, javax.swing.GroupLayout.Alignment.LEADING))))))
                .addContainerGap(61, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(lblTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBuscar1)
                    .addComponent(lblFiltroAño1)
                    .addComponent(txtFiltrarAnio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblImagen1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42)
                        .addComponent(lblImagen2, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblNombre1)
                            .addComponent(lblTextNombre1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblMarca1)
                            .addComponent(lblTextMarca1))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblModelo1)
                            .addComponent(lblTextModelo1))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblPrecio1)
                            .addComponent(lblTextPrecio1))
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblNombre2)
                            .addComponent(lblTextNombre2, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblMarca2)
                            .addComponent(lblTextMarca2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblModelo2)
                            .addComponent(lblTextModelo2))
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblPrecio2)
                            .addComponent(lblTextPrecio2)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnVer1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(82, 82, 82)
                        .addComponent(btnVer2, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblAnio1)
                            .addComponent(lblTextAnio1))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblMotor1)
                            .addComponent(lblTextMotor1))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblPlaca1)
                            .addComponent(lblTextPlaca1))
                        .addGap(75, 75, 75)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblAnio2)
                            .addComponent(lblTextAnio2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblMotor2)
                            .addComponent(lblTextMotor2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblPlaca2)
                            .addComponent(lblTextPlaca2))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblAnio3)
                                    .addComponent(lblTextAnio3))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblMotor3)
                                    .addComponent(lblTextMotor3))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblPlaca3)
                                    .addComponent(lblTextPlaca3)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblNombre3)
                                    .addComponent(lblTextNombre3, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblMarca3)
                                    .addComponent(lblTextMarca3))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblModelo3)
                                    .addComponent(lblTextModelo3))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblPrecio3)
                            .addComponent(lblTextPrecio3)))
                    .addComponent(btnVer3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblImagen3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(btnAnterior)
                    .addComponent(btnSiguiente))
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAnteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnteriorActionPerformed
        JOptionPane.showMessageDialog(this,"Estas en la página #1");
    }//GEN-LAST:event_btnAnteriorActionPerformed

    private void btnBuscar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBuscar1ActionPerformed

    private void btnSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSiguienteActionPerformed
        CambiarPagina();
    }//GEN-LAST:event_btnSiguienteActionPerformed

    private void btnVer1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVer1ActionPerformed
        abrirVerInfo();
        /*
        try {
            cambiarPlaca.setEnviarPlaca("PDP01");
            abrirFormulario();
        } catch (Exception ex) {
            Logger.getLogger(Frm_Vehiculos1.class.getName()).log(Level.SEVERE, null, ex);
        }
        */

    }//GEN-LAST:event_btnVer1ActionPerformed

    private void btnVer2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVer2ActionPerformed
        abrirVerInfo();
        /*
        try {
            cambiarPlaca.setEnviarPlaca("PHD02");
            System.out.println(""+cambiarPlaca.getEnviarPlaca());
        } catch (Exception ex) {
            Logger.getLogger(Frm_Vehiculos1.class.getName()).log(Level.SEVERE, null, ex);
        }
        */
    }//GEN-LAST:event_btnVer2ActionPerformed

    private void btnVer3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVer3ActionPerformed
        abrirVerInfo();
        /*
        try {
            cambiarPlaca.setEnviarPlaca("PDZ90");
            abrirFormulario();
        } catch (Exception ex) {
            Logger.getLogger(Frm_Vehiculos1.class.getName()).log(Level.SEVERE, null, ex);
        }
        */
    }//GEN-LAST:event_btnVer3ActionPerformed

    public void CambiarPagina(){
        Frm_Vehiculos2 abrirOtroFormulario = new Frm_Vehiculos2();
        abrirOtroFormulario.setDefaultCloseOperation(HIDE_ON_CLOSE);
        abrirOtroFormulario.setVisible(true);
        this.setVisible(false);
    }
    
    public void abrirVerInfo(){
        Frm_VerInfo abrirVerInfo = new Frm_VerInfo();
        abrirVerInfo.setDefaultCloseOperation(HIDE_ON_CLOSE);
        abrirVerInfo.setVisible(true);
        this.setVisible(false);
    }
    
    public void info(){
        VehiculoRepo vr = new VehiculoRepo();
        try {
            Vehiculo valorBuscado = vr.seleccionar("PDP01");
            lblTextNombre1.setText(String.valueOf(valorBuscado.getNombre()));
            lblTextMarca1.setText(String.valueOf(valorBuscado.getMarca()));
            lblTextModelo1.setText(String.valueOf(valorBuscado.getModelo()));
            lblTextPrecio1.setText(String.valueOf(valorBuscado.getPrecio()));
            lblTextAnio1.setText(String.valueOf(valorBuscado.getAnio()));
            lblTextMotor1.setText(String.valueOf(valorBuscado.getMotor()));
            lblTextPlaca1.setText(String.valueOf(valorBuscado.getPlaca()));
            String imagen1 = valorBuscado.getImagen();
            ImageIcon carro1 = new ImageIcon(getClass().getResource(imagen1));
            ImageIcon icono1 = new ImageIcon(carro1.getImage().getScaledInstance(lblImagen1.getWidth(), lblImagen1.getHeight(), Image.SCALE_DEFAULT) );
            //System.out.println(""+icono1);
            lblImagen1.setIcon(icono1);
            
            Vehiculo valorBuscado2 = vr.seleccionar("PHD02");
            lblTextNombre2.setText(String.valueOf(valorBuscado2.getNombre()));
            lblTextMarca2.setText(String.valueOf(valorBuscado2.getMarca()));
            lblTextModelo2.setText(String.valueOf(valorBuscado2.getModelo()));
            lblTextPrecio2.setText(String.valueOf(valorBuscado2.getPrecio()));
            lblTextAnio2.setText(String.valueOf(valorBuscado2.getAnio()));
            lblTextMotor2.setText(String.valueOf(valorBuscado2.getMotor()));
            lblTextPlaca2.setText(String.valueOf(valorBuscado2.getPlaca()));
            String imagen2 = valorBuscado2.getImagen();
            ImageIcon carro2 = new ImageIcon(getClass().getResource(imagen2));
            ImageIcon icono2 = new ImageIcon(carro2.getImage().getScaledInstance(lblImagen2.getWidth(), lblImagen2.getHeight(), Image.SCALE_DEFAULT) );
            //System.out.println(""+icono2);
            lblImagen2.setIcon(icono2);
            
            Vehiculo valorBuscado3 = vr.seleccionar("PDZ90");
            lblTextNombre3.setText(String.valueOf(valorBuscado3.getNombre()));
            lblTextMarca3.setText(String.valueOf(valorBuscado3.getMarca()));
            lblTextModelo3.setText(String.valueOf(valorBuscado3.getModelo()));
            lblTextPrecio3.setText(String.valueOf(valorBuscado3.getPrecio()));
            lblTextAnio3.setText(String.valueOf(valorBuscado3.getAnio()));
            lblTextMotor3.setText(String.valueOf(valorBuscado3.getMotor()));
            lblTextPlaca3.setText(String.valueOf(valorBuscado3.getPlaca()));
                String imagen3 = valorBuscado3.getImagen();
                ImageIcon carro3 = new ImageIcon(getClass().getResource(imagen3));
                ImageIcon icono3 = new ImageIcon(carro3.getImage().getScaledInstance(lblImagen3.getWidth(), lblImagen3.getHeight(), Image.SCALE_DEFAULT) );
                //System.out.println(""+icono3);
                lblImagen3.setIcon(icono3);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,e.toString());
        }
    }
    
    
    
     
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frm_Vehiculos1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frm_Vehiculos1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frm_Vehiculos1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frm_Vehiculos1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frm_Vehiculos1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAnterior;
    private javax.swing.JButton btnBuscar1;
    private javax.swing.JButton btnSiguiente;
    private javax.swing.JButton btnVer1;
    private javax.swing.JButton btnVer2;
    private javax.swing.JButton btnVer3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblAnio1;
    private javax.swing.JLabel lblAnio2;
    private javax.swing.JLabel lblAnio3;
    private javax.swing.JLabel lblFiltroAño1;
    private javax.swing.JLabel lblImagen1;
    private javax.swing.JLabel lblImagen2;
    private javax.swing.JLabel lblImagen3;
    private javax.swing.JLabel lblMarca1;
    private javax.swing.JLabel lblMarca2;
    private javax.swing.JLabel lblMarca3;
    private javax.swing.JLabel lblModelo1;
    private javax.swing.JLabel lblModelo2;
    private javax.swing.JLabel lblModelo3;
    private javax.swing.JLabel lblMotor1;
    private javax.swing.JLabel lblMotor2;
    private javax.swing.JLabel lblMotor3;
    private javax.swing.JLabel lblNombre1;
    private javax.swing.JLabel lblNombre2;
    private javax.swing.JLabel lblNombre3;
    private javax.swing.JLabel lblPlaca1;
    private javax.swing.JLabel lblPlaca2;
    private javax.swing.JLabel lblPlaca3;
    private javax.swing.JLabel lblPrecio1;
    private javax.swing.JLabel lblPrecio2;
    private javax.swing.JLabel lblPrecio3;
    private javax.swing.JLabel lblTextAnio1;
    private javax.swing.JLabel lblTextAnio2;
    private javax.swing.JLabel lblTextAnio3;
    private javax.swing.JLabel lblTextMarca1;
    private javax.swing.JLabel lblTextMarca2;
    private javax.swing.JLabel lblTextMarca3;
    private javax.swing.JLabel lblTextModelo1;
    private javax.swing.JLabel lblTextModelo2;
    private javax.swing.JLabel lblTextModelo3;
    private javax.swing.JLabel lblTextMotor1;
    private javax.swing.JLabel lblTextMotor2;
    private javax.swing.JLabel lblTextMotor3;
    private javax.swing.JLabel lblTextNombre1;
    private javax.swing.JLabel lblTextNombre2;
    private javax.swing.JLabel lblTextNombre3;
    public static javax.swing.JLabel lblTextPlaca1;
    public static javax.swing.JLabel lblTextPlaca2;
    public static javax.swing.JLabel lblTextPlaca3;
    private javax.swing.JLabel lblTextPrecio1;
    private javax.swing.JLabel lblTextPrecio2;
    private javax.swing.JLabel lblTextPrecio3;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTextField txtFiltrarAnio;
    // End of variables declaration//GEN-END:variables
}
